#ifndef LABWORK1_VYACHESLAV_ATAMANYUK_COMAND_PARSER_H
#define LABWORK1_VYACHESLAV_ATAMANYUK_COMAND_PARSER_H
void ComandParser(int argc, char** argv);
#endif //LABWORK1_VYACHESLAV_ATAMANYUK_COMAND_PARSER_H
