#ifndef LABWORK1_VYACHESLAV_ATAMANYUK_FILE_PARSER_H
#define LABWORK1_VYACHESLAV_ATAMANYUK_FILE_PARSER_H
#include "comand_parser.h"
void PrintFile(Arguments args);
#endif //LABWORK1_VYACHESLAV_ATAMANYUK_FILE_PARSER_H
